import { put } from "@vercel/blob";
import { distKm } from "./alert-common.mjs";
import { attachGoEventEvidence, loadRecentGoEvents } from "./go-event-common.mjs";

const ALERTWEST_URL = "https://alertwest.live/api/firecams/v0/cameras";
const CREDIT = "ALERTWest's Situational Awareness Platform";
const HEADERS = { "User-Agent": "RainbowConnector/1.0 (noncommercial weather research)" };
export function angleDifference(a, b) { return Math.abs((Number(a) - Number(b) + 540) % 360 - 180); }
const safeHttps = value => /^https:\/\//i.test(String(value || "")) ? String(value) : null;
export function parseAlertWestCameras(payload) {
  return (Array.isArray(payload) ? payload : []).map(camera => { const site = camera.site || {}, image = camera.image || {}, position = camera.position || {}; const observed = new Date(image.time); return { id: `alertwest-${camera.source || camera.name || site.id}`, name: camera.name || camera.source || `ALERTWest camera ${site.id || "unknown"}`, siteId: site.id || null, lat: Number(site.latitude), lon: Number(site.longitude), pan: Number(position.pan), tilt: Number(position.tilt), observedAt: Number.isFinite(observed.getTime()) ? observed.toISOString() : null, imageUrl: safeHttps(image.url), state: site.state || null, pageUrl: "https://alertwest.live/", viewLine: camera.view?.line || null, offline: camera.offline === true || camera.offline === 1 }; }).filter(camera => camera.id !== "alertwest-undefined" && !camera.offline && camera.imageUrl && Number.isFinite(camera.lat) && Number.isFinite(camera.lon) && Number.isFinite(camera.pan));
}
export async function loadAlertWestCameras() { const response = await fetch(ALERTWEST_URL, { headers: HEADERS, cache: "no-store" }); if (!response.ok) throw new Error(`ALERTWest camera list failed (${response.status})`); return parseAlertWestCameras(await response.json()); }
export function matchAlertWestCameras(event, cameras, options = {}) { const rep = event?.representative || {}, bearing = Number(rep.direction?.bearing); if (!Number.isFinite(rep.lat) || !Number.isFinite(rep.lon) || !Number.isFinite(bearing)) return []; const maxDistanceKm = Number(options.maxDistanceKm || 35), maxBearingDifference = Number(options.maxBearingDifference || 32), limit = Math.max(1, Math.min(Number(options.limit) || 3, 5)); return (cameras || []).map(camera => ({ camera, distanceKm: distKm(rep.lat, rep.lon, camera.lat, camera.lon), bearingDifference: angleDifference(camera.pan, bearing) })).filter(match => match.distanceKm <= maxDistanceKm && match.bearingDifference <= maxBearingDifference).sort((a, b) => a.distanceKm + a.bearingDifference * 0.35 - (b.distanceKm + b.bearingDifference * 0.35)).slice(0, limit); }
export function nearbyAlertWestCameras(event, cameras, maxDistanceKm = 35) { const rep = event?.representative || {}; if (!Number.isFinite(rep.lat) || !Number.isFinite(rep.lon)) return []; return (cameras || []).map(camera => ({ camera, distanceKm: distKm(rep.lat, rep.lon, camera.lat, camera.lon) })).filter(match => match.distanceKm <= maxDistanceKm).sort((a, b) => a.distanceKm - b.distanceKm); }
async function storeFrame(event, match) { const imageUrl = `${match.camera.imageUrl}${match.camera.imageUrl.includes("?") ? "&" : "?"}rc=${Date.now()}`; const response = await fetch(imageUrl, { headers: HEADERS, cache: "no-store" }); if (!response.ok || !String(response.headers.get("content-type") || "").toLowerCase().includes("image/")) throw new Error(`ALERTWest image failed (${response.status})`); const bytes = await response.arrayBuffer(); if (bytes.byteLength < 12000 || bytes.byteLength > 5000000) throw new Error("ALERTWest image size was unsuitable."); const observedAt = match.camera.observedAt || new Date().toISOString(); const centerMs = new Date(event.representative?.detectedAt || event.firstSeenAt).getTime(); const timeOffsetMinutes = Number(((new Date(observedAt).getTime() - centerMs) / 60000).toFixed(1)); const stamp = observedAt.replace(/[^0-9]/g, "").slice(0, 17); const stored = await put(`go-evidence/${event.id}/alertwest-${match.camera.id}-${stamp}.jpg`, bytes, { access: "public", addRandomSuffix: false, allowOverwrite: true, contentType: "image/jpeg" }); return { url: stored.url, observedAt, source: CREDIT, cameraId: match.camera.id, cameraName: match.camera.name, cameraPageUrl: match.camera.pageUrl, distanceKm: Number(match.distanceKm.toFixed(1)), bearingDifference: Number(match.bearingDifference.toFixed(1)), direction: `Camera faced ${match.camera.pan.toFixed(1)}° at capture`, publishedDirection: match.camera.viewLine, state: match.camera.state, viewQuality: "usable", cameraPan: Number(match.camera.pan.toFixed(1)), cameraTilt: Number.isFinite(match.camera.tilt) ? Number(match.camera.tilt.toFixed(1)) : null, timeOffsetMinutes, attribution: CREDIT }; }
export async function captureAlertWestEvidence(event, cameras) { if ((event?.evidence?.frames || []).length) return { stored: false, reason: "already_captured", eventId: event.id }; const nearby = nearbyAlertWestCameras(event, cameras); if (!nearby.length) return { stored: false, reason: "no_alertwest_match", eventId: event.id }; const aligned = matchAlertWestCameras(event, cameras); if (!aligned.length) { const nearest = nearby[0]; await attachGoEventEvidence(event.id, { status: "waiting_alertwest", source: CREDIT, camera: { id: nearest.camera.id, name: nearest.camera.name, state: nearest.camera.state, direction: "Waiting for the camera to face the predicted rainbow", distanceKm: Number(nearest.distanceKm.toFixed(1)), viewQuality: "usable" } }); return { stored: false, reason: "waiting_for_aligned_alertwest_view", eventId: event.id }; } const frames = (await Promise.allSettled(aligned.map(match => storeFrame(event, match)))).filter(result => result.status === "fulfilled").map(result => result.value); if (!frames.length) return { stored: false, reason: "no_usable_alertwest_frames", eventId: event.id }; const primary = frames.sort((a, b) => a.distanceKm + a.bearingDifference * 0.35 - (b.distanceKm + b.bearingDifference * 0.35))[0]; const nearestFrameOffsetMinutes = Math.min(...frames.map(frame => Math.abs(frame.timeOffsetMinutes))); await attachGoEventEvidence(event.id, { status: "ready", source: CREDIT, camera: { id: primary.cameraId, name: primary.cameraName, state: primary.state, direction: primary.direction, distanceKm: primary.distanceKm, bearingDifference: primary.bearingDifference, viewQuality: "usable", nearestFrameOffsetMinutes, attribution: CREDIT }, frames }); return { stored: true, eventId: event.id, frames: frames.length, source: CREDIT }; }
export async function capturePendingAlertWestEvidence(limit = 2) { const cameras = await loadAlertWestCameras(), now = Date.now(); const pending = (await loadRecentGoEvents(now - 45 * 60 * 1000, 50)).filter(event => (event.review?.label || "pending") === "pending").filter(event => !(event.evidence?.frames || []).length).filter(event => nearbyAlertWestCameras(event, cameras).length).sort((a, b) => Number(b.peakScore || 0) - Number(a.peakScore || 0)).slice(0, Math.max(0, Math.min(Number(limit) || 2, 4))); const results = []; for (const event of pending) { try { results.push(await captureAlertWestEvidence(event, cameras)); } catch (error) { results.push({ stored: false, eventId: event.id, reason: error.message || "alertwest_capture_failed" }); } } return results; }
