import { put } from "@vercel/blob";
import { distKm } from "./alert-common.mjs";
import { attachGoEventEvidence, loadRecentGoEvents } from "./go-event-common.mjs";

const GEOJSON_URL = "https://api.nysmesonet.org/data/index.php/geojson/nysm/latest";
const CAM_URL = "https://api.nysmesonet.org/cam/index.php/list/nysm";
const CREDIT = "New York State Mesonet | University at Albany";
const HEADERS = { "User-Agent": "RainbowConnector/1.0 (noncommercial weather research)" };
export function angleDifference(a, b) { return Math.abs((Number(a) - Number(b) + 540) % 360 - 180); }
export function parseNysmStations(payload) { return (payload?.features || []).map(feature => { const p = feature.properties || {}, [lon, lat] = feature.geometry?.coordinates || []; return { id: `nysm-${p.STID}`, stationId: p.STID, name: p.NAME || p.STID, lat: Number(p.LAT ?? lat), lon: Number(p.LON ?? lon), state: "NY", pageUrl: `https://nysmesonet.org/weather/#?network=nysm&stid=${encodeURIComponent(p.STID || "")}` }; }).filter(camera => camera.id !== "nysm-undefined" && Number.isFinite(camera.lat) && Number.isFinite(camera.lon)); }
export function parseNysmPhotos(station, payload) { return (payload?.photos || []).map(photo => ({ ...station, id: `${station.id}-${photo.timestamp}`, imageUrl: photo.url, observedAt: new Date(Number(photo.timestamp) * 1000).toISOString(), pan: Number(photo.direction), fixedView: true })).filter(camera => /^https:\/\//i.test(String(camera.imageUrl || "")) && Number.isFinite(camera.pan) && Number.isFinite(new Date(camera.observedAt).getTime())); }
async function loadStationPhotos(station, start, end) { const response = await fetch(`${CAM_URL}/${encodeURIComponent(station.stationId)}/${start}/${end}`, { headers: HEADERS, cache: "no-store" }); if (!response.ok) return []; return parseNysmPhotos(station, await response.json()); }
export async function loadNysmCameras() { const stations = parseNysmStations(await (await fetch(GEOJSON_URL, { headers: HEADERS, cache: "no-store" })).json()); const end = new Date(), start = new Date(end.getTime() - 4200 * 1000); const fmt = value => value.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, ""); return (await Promise.all(stations.map(station => loadStationPhotos(station, fmt(start), fmt(end))))).flat().sort((a, b) => b.observedAt.localeCompare(a.observedAt)); }
export async function loadNysmHistoricalPhotos(station, startDate, endDate) { const start = Math.floor(new Date(startDate).getTime() / 1000), end = Math.floor(new Date(endDate).getTime() / 1000); return loadStationPhotos(station, `${new Date(start * 1000).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "")}`, `${new Date(end * 1000).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "")}`); }
export function matchNysmCameras(event, cameras, options = {}) { const rep = event?.representative || {}, bearing = Number(rep.direction?.bearing); if (!Number.isFinite(rep.lat) || !Number.isFinite(rep.lon) || !Number.isFinite(bearing)) return []; const maxDistanceKm = Number(options.maxDistanceKm || 35), maxBearingDifference = Number(options.maxBearingDifference || 55), limit = Math.max(1, Math.min(Number(options.limit) || 3, 5)); return (cameras || []).map(camera => ({ camera, distanceKm: distKm(rep.lat, rep.lon, camera.lat, camera.lon), bearingDifference: angleDifference(camera.pan, bearing) })).filter(match => match.distanceKm <= maxDistanceKm && match.bearingDifference <= maxBearingDifference).sort((a, b) => a.distanceKm + a.bearingDifference * 0.35 - (b.distanceKm + b.bearingDifference * 0.35)).slice(0, limit); }
export function nearbyNysmCameras(event, cameras, maxDistanceKm = 35) { const rep = event?.representative || {}; if (!Number.isFinite(rep.lat) || !Number.isFinite(rep.lon)) return []; return (cameras || []).map(camera => ({ camera, distanceKm: distKm(rep.lat, rep.lon, camera.lat, camera.lon) })).filter(match => match.distanceKm <= maxDistanceKm).sort((a, b) => a.distanceKm - b.distanceKm); }
async function storeFrame(event, match) { const response = await fetch(`${match.camera.imageUrl}?branding=true`, { headers: HEADERS, cache: "no-store" }); if (!response.ok || !String(response.headers.get("content-type") || "").toLowerCase().includes("image/")) throw new Error(`NYS Mesonet image failed (${response.status})`); const bytes = await response.arrayBuffer(); if (bytes.byteLength < 8000 || bytes.byteLength > 5000000) throw new Error("NYS Mesonet image size was unsuitable."); const observedAt = match.camera.observedAt; const centerMs = new Date(event.representative?.detectedAt || event.firstSeenAt).getTime(); const timeOffsetMinutes = Number(((new Date(observedAt).getTime() - centerMs) / 60000).toFixed(1)); const stamp = observedAt.replace(/[^0-9]/g, "").slice(0, 17); const stored = await put(`go-evidence/${event.id}/nysm-${match.camera.stationId}-${stamp}.jpg`, bytes, { access: "public", addRandomSuffix: false, allowOverwrite: true, contentType: "image/jpeg" }); return { url: stored.url, observedAt, source: CREDIT, cameraId: match.camera.stationId, cameraName: match.camera.name, cameraPageUrl: match.camera.pageUrl, distanceKm: Number(match.distanceKm.toFixed(1)), bearingDifference: Number(match.bearingDifference.toFixed(1)), direction: `Fixed camera faces ${match.camera.pan.toFixed(1)}°`, state: "NY", cameraPan: Number(match.camera.pan.toFixed(1)), viewQuality: "usable", timeOffsetMinutes, attribution: CREDIT }; }
export async function captureNysmEvidence(event, cameras) { if ((event?.evidence?.frames || []).length) return { stored: false, reason: "already_captured", eventId: event.id }; const aligned = matchNysmCameras(event, cameras); if (!aligned.length) return { stored: false, reason: "no_nysm_match", eventId: event.id }; const frames = (await Promise.allSettled(aligned.map(match => storeFrame(event, match)))).filter(result => result.status === "fulfilled").map(result => result.value); if (!frames.length) return { stored: false, reason: "no_usable_nysm_frames", eventId: event.id }; const primary = frames[0], nearestFrameOffsetMinutes = Math.min(...frames.map(frame => Math.abs(frame.timeOffsetMinutes))); await attachGoEventEvidence(event.id, { status: "ready", source: CREDIT, camera: { id: primary.cameraId, name: primary.cameraName, state: "NY", direction: primary.direction, distanceKm: primary.distanceKm, bearingDifference: primary.bearingDifference, viewQuality: "usable", nearestFrameOffsetMinutes, attribution: CREDIT }, frames }); return { stored: true, eventId: event.id, frames: frames.length, source: CREDIT }; }
export async function capturePendingNysmEvidence(limit = 2) { const cameras = await loadNysmCameras(), now = Date.now(); const pending = (await loadRecentGoEvents(now - 45 * 60 * 1000, 50)).filter(event => (event.review?.label || "pending") === "pending").filter(event => !(event.evidence?.frames || []).length).filter(event => nearbyNysmCameras(event, cameras).length).sort((a, b) => Number(b.peakScore || 0) - Number(a.peakScore || 0)).slice(0, Math.max(0, Math.min(Number(limit) || 2, 4))); const results = []; for (const event of pending) { try { results.push(await captureNysmEvidence(event, cameras)); } catch (error) { results.push({ stored: false, eventId: event.id, reason: error.message || "nysm_capture_failed" }); } } return results; }
